parameters:
    base_url: ''
    test_config_used: true
# doctrine:
#     dbal:
#         driver: pdo_mysql
#         host: localhost
#         port: 3306
#         dbname: app_name
#         user: user
#         password: pass
